version: '2'
services:
  frontend:
    build: .
    # image: ghcr.io/rustygreen/raspberry-pi-client:main
    ports:
      - '3000:80'
    environment:
      # The configuration will consist of one server with URL/title:
      # - 'RPC_SERVER=https://pi-basement.rusty.green'
      # - 'RPC_SERVER_TITLE=Basement Pi'
      - 'RPC_CONFIG={"servers": [{"title": "Basement Pi","url": "https://pi-basement.rusty.green","pinLabels": {"11": "Cows water","17": "Cows water drain","13": "Chickens water","31": "Chickens water drain"}}]}'
