# name: Create and publish a Docker image

# on:
#   workflow_run:
#     workflows: ['Build and Test']
#     branches: [main]
#     types:
#       - completed
#   push:
#     branches: ['main']

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}
#   IMAGE_TARGET_PLATFORM: linux/amd64,linux/arm/v7,linux/arm64

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - uses: actions/download-artifact@v3
#         with:
#           name: deploy_dist

#       - name: Display structure of downloaded files
#         run: ls -R
# # jobs:
# #   build-and-push-image:
# #     runs-on: ubuntu-latest
# #     permissions:
# #       contents: read
# #       packages: write

# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v3

# #       - name: Log in to the Container registry
# #         uses: docker/login-action@v1
# #         with:
# #           registry: ${{ env.REGISTRY }}
# #           username: ${{ github.actor }}
# #           password: ${{ secrets.GITHUB_TOKEN }}

# #       - name: Extract metadata (tags, labels) for Docker
# #         id: meta
# #         uses: docker/metadata-action@v3
# #         with:
# #           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

# #       - name: Setup Docker Buildx
# #         uses: docker/setup-buildx-action@v1

# #       - name: Set up QEMU
# #         uses: docker/setup-qemu-action@v1

# #       - name: Build and push Docker image
# #         uses: docker/build-push-action@v2
# #         with:
# #           context: .
# #           push: true
# #           platforms: ${{ env.IMAGE_TARGET_PLATFORM }}
# #           tags: ${{ steps.meta.outputs.tags }}
# #           labels: ${{ steps.meta.outputs.labels }}
